### ISSUE TITLE
how to ask SINA to save taxonomy search results from multiple runs into 1 file, but not save alignments?

### ISSUE THREAD

**Issue by l-yampolsky** [epruesse/SINA#80] opened 2019-12-03 20:22 UTC
If I do

for f in *.fasta;
do
    [PATH2SINA]/sina -i $f    \
    -r [PATH2SILVA.arb]      \
    -o outfile                    \
    -t --search --search-max-result=1 --lca-fields=tax_slv --meta-fmt=csv >> silvaResults.csv ;
done;

-clearly it overwrites the outfile each time and nothing goes into silvaResults.csv.

If I do 

for f in *.fasta;
do
    [PATH2SINA]/sina -i $f    \
    -r [PATH2SILVA.arb]      \
    -o -                    \ #of omit -o altogether
    -t --search --search-max-result=1 --lca-fields=tax_slv --meta-fmt=csv >> silvaResults.csv ;
done;

then, instead of appending to silvaResults.csv, SINA appends to -.csv. There are two problems with that: 1)everything gets dumped into -.csv, inlcuding the alignments and 2) the file -csv has to be manually renamed before it can be used in scripts.

Is there a way to suppress output of the alignments and to give the default output file some other name?

Thanks!!

**Comment by epruesse** [comment] 2019-12-05 19:38
What you want will work with 1.6.1 more easily. There, you can just say

```
sina .... -o output1.csv
```

It might just be easiest to wait until then.

**Comment by epruesse** [comment] 2019-12-05 19:38
Considering duplicate of #10

**Closed as completed by epruesse** 2019-12-05 19:38 UTC
